{
    "load": {
        "insertComplete": false,
        "Exceptions": {
            "total": 797,
            "Caused by: java.util.concurrent.TimeoutException": 163,
            "java.lang.RuntimeException": 163,
            "com.couchbase.client.java.error.DocumentAlreadyExistsException": 471
        },
        "insertRetryError": 157,
        "INSERT-FAILED": 634
    },
    "run": {
        "executionTimeReached": false,
        "Exceptions": {
            "total": 2711,
            "\t... 8 moresite.ycsb.DBException": 1,
            "\tat com.couchbase.client.java.util.Blocking.blockForSingle(Blocking.java:71)Caused by: java.lang.RuntimeException": 1,
            "\tat java.lang.Thread.run(Thread.java:748)Caused by: java.util.concurrent.TimeoutException": 1,
            "\tat com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:290)site.ycsb.DBException": 1,
            "\tat site.ycsb.db.couchbase2.Couchbase2Client.init(Couchbase2Client.java:208)Caused by: java.util.concurrent.TimeoutException": 1,
            "\tat com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:260)site.ycsb.DBException": 1,
            "\tat site.ycsb.db.couchbase2.Couchbase2Client.init(Couchbase2Client.java:205)site.ycsb.DBException": 1,
            "\tat site.ycsb.ClientThread.run(ClientThread.java:91)site.ycsb.DBException": 1,
            "\tat site.ycsb.DBWrapper.init(DBWrapper.java:86)Caused by: java.util.concurrent.TimeoutException": 1,
            "\tat java.lang.Thread.run(Thread.java:748)Caused by: java.lang.RuntimeException": 2,
            "\t... 8 moreCaused by: java.lang.RuntimeException": 3,
            "\t... 8 moreCaused by: java.util.concurrent.TimeoutException": 3,
            "\t... 3 moreCaused by: java.lang.RuntimeException": 4,
            "\t... 3 moreCaused by: java.util.concurrent.TimeoutException": 4,
            "\tat com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:260)Caused by: java.util.concurrent.TimeoutException": 5,
            "\tat site.ycsb.DBWrapper.init(DBWrapper.java:86)site.ycsb.DBException": 5,
            "\tat site.ycsb.db.couchbase2.Couchbase2Client.init(Couchbase2Client.java:205)Caused by: java.util.concurrent.TimeoutException": 6,
            "\tat com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:271)Caused by: java.lang.RuntimeException": 10,
            "\tat com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:290)Caused by: java.lang.RuntimeException": 12,
            "\tat site.ycsb.db.couchbase2.Couchbase2Client.init(Couchbase2Client.java:205)Caused by: java.lang.RuntimeException": 12,
            "\tat com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:290)Caused by: java.util.concurrent.TimeoutException": 14,
            "\tat site.ycsb.db.couchbase2.Couchbase2Client.init(Couchbase2Client.java:208)Caused by: java.lang.RuntimeException": 15,
            "\tat com.couchbase.client.java.util.Blocking.blockForSingle(Blocking.java:71)Caused by: java.util.concurrent.TimeoutException": 17,
            "\tat com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:271)Caused by: java.util.concurrent.TimeoutException": 18,
            "\tat com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:260)Caused by: java.lang.RuntimeException": 19,
            "\tat site.ycsb.ClientThread.run(ClientThread.java:91)Caused by: java.lang.RuntimeException": 31,
            "\tat site.ycsb.DBWrapper.init(DBWrapper.java:86)Caused by: java.lang.RuntimeException": 39,
            "\tat site.ycsb.db.couchbase2.Couchbase2Client.init(Couchbase2Client.java:208)site.ycsb.DBException": 45,
            "Caused by: java.lang.RuntimeException": 422,
            "java.lang.RuntimeException": 505,
            "site.ycsb.DBException": 511,
            "Caused by: java.util.concurrent.TimeoutException": 1000
        },
        "insertRetryError": 0,
        "INSERT-FAILED": 236,
        "READ-FAILED": 311
    }
}